# Generated by Django 2.2.3 on 2019-08-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20190827_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
