# Generated by Django 2.2.3 on 2019-08-17 05:46

import ckeditor_uploader.fields
from django.db import migrations, models
import location_field.models.plain
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='eventos/', verbose_name='Foto')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción')),
                ('init_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('init_hour', models.TimeField(verbose_name='Hora de inicio')),
                ('end_hour', models.TimeField(verbose_name='Hora de fin')),
                ('reference_point', models.CharField(max_length=100, verbose_name='Punto de referencia')),
                ('position', location_field.models.plain.PlainLocationField(max_length=63, verbose_name='Posición')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'verbose_name': 'Evento',
            },
        ),
    ]
