# Generated by Django 2.2.3 on 2019-08-17 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Separar elementos con ","', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
