# Generated by Django 2.2.3 on 2019-08-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_auto_20190811_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
