# Generated by Django 2.2.3 on 2019-08-12 04:09

import ckeditor_uploader.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Título')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='recursos-educativos/', verbose_name='Foto')),
                ('slug', models.SlugField(editable=False, max_length=200)),
            ],
            options={
                'verbose_name': 'Recurso educativo',
                'verbose_name_plural': 'Recursos educativos',
            },
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Título')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='aprende/', verbose_name='Foto')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('slug', models.SlugField(editable=False, max_length=200)),
            ],
            options={
                'verbose_name': 'Aprende',
                'verbose_name_plural': 'Aprende',
            },
        ),
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
    ]
