# Generated by Django 2.2.3 on 2019-08-17 05:46

import ckeditor_uploader.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Título')),
                ('photo', sorl.thumbnail.fields.ImageField(blank=True, upload_to='recursos-educativos/', verbose_name='Foto')),
                ('info_type', models.PositiveSmallIntegerField(choices=[(1, 'ETS'), (2, 'Embarazo')], verbose_name='Categoría')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('slug', models.SlugField(editable=False, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Recursos educativos',
                'verbose_name': 'Recurso educativo',
            },
        ),
        migrations.CreateModel(
            name='EduFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350)),
                ('archivo_pdf', models.FileField(upload_to='recursos-educativos/archivos/')),
            ],
            options={
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Título')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='recursos-educativos/aprende', verbose_name='Foto')),
                ('info_type', models.PositiveSmallIntegerField(choices=[(1, 'ETS'), (2, 'Embarazo')], verbose_name='Categoría')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('slug', models.SlugField(editable=False, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Aprende',
                'verbose_name': 'Aprende',
            },
        ),
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Temas',
                'verbose_name': 'Tema',
            },
        ),
    ]
