# Generated by Django 2.2.3 on 2019-08-17 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_educativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='learning',
            name='thematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_educativos.Thematic', verbose_name='Temática'),
        ),
        migrations.AddField(
            model_name='edufiles',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_educativos.Educational_Resource', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='educational_resource',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='educational_resource',
            name='thematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_educativos.Thematic', verbose_name='Temática'),
        ),
    ]
