# Generated by Django 2.2.3 on 2019-08-13 05:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_educativos', '0003_auto_20190812_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_resource',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
