# Generated by Django 2.2.3 on 2019-08-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_educativos', '0004_educational_resource_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_resource',
            name='thematic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_educativos.Thematic', verbose_name='Temática'),
            preserve_default=False,
        ),
    ]
