# Generated by Django 2.2.3 on 2019-08-15 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_educativos', '0005_educational_resource_thematic'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_resource',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
