# Generated by Django 2.2.3 on 2019-08-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoColaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_colaborador', models.CharField(max_length=250, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Colaboradores',
                'verbose_name': 'Tipo de Colaborador',
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colaborador.TipoColaborador', verbose_name='Tipo de Colaborador'),
            preserve_default=False,
        ),
    ]
